# Pre-provisioned NFS PV for Frigate surveillance storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-surveillance
  nfs:
    server: TRUENAS_IP_PLACEHOLDER
    path: /mnt/surveillance/frigate
---
# HuggingFace cache for ML models (shared across namespaces via NFS)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: huggingface-cache-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-models
  nfs:
    server: TRUENAS_IP_PLACEHOLDER
    path: /mnt/fast/models
