# Optional NFS Storage Classes
# Deploy these when the corresponding NFS shares are configured

---
# NFS Storage Class for backups
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-backups
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/data/backups
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for archive (cold tier for SeaweedFS)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-archive
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/data/archive
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for surveillance data (Frigate)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-surveillance
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/surveillance/frigate
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
