# Core NFS Storage Classes
# These are commonly used and should be deployed when NFS is ready

---
# NFS Storage Class for general data
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-data
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/data/data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for fast storage (databases, caches, performance-critical workloads)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-fast
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/fast/data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for AI models cache (shared across AI containers)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-models
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/fast/models
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
