# Storage Classes for Homelab
#
# NFS Storage Classes (this file) - use NFS CSI driver for TrueNAS storage
# Local Storage Classes (local-path-config.yaml):
#   - nvme-fast: /mnt/nvme-fast (for databases, caches, performance-critical)
#   - scratch: /mnt/scratch (for temporary/ephemeral data)
#   - nfs-models: /mnt/fast/models (for AI model cache, shared across containers)
#
# NFS Storage Classes

---
# NFS Storage Class for general data
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-data
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/data/data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for backups
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-backups
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/data/backups
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for archive
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-archive
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/data/archive
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for surveillance data (Frigate)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-surveillance
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/surveillance/frigate
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime

---
# NFS Storage Class for AI models cache (shared across AI containers)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-models
provisioner: nfs.csi.k8s.io
parameters:
  server: TRUENAS_IP_PLACEHOLDER
  share: /mnt/fast/models
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
