apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-cert
  namespace: immich
spec:
  secretName: immich-tls
  commonName: immich.apps.house.simonellistonball.com
  dnsNames:
    - immich.apps.house.simonellistonball.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  subject:
    organizations:
      - Simon Elliston Ball
    organizationalUnits:
      - homelab
