# Immich Machine Learning - handles face recognition, smart search, etc.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:release
          imagePullPolicy: Always
          env:
            - name: IMMICH_HOST
              value: "0.0.0.0"
            - name: IMMICH_PORT
              value: "3003"
            - name: MACHINE_LEARNING_CACHE_FOLDER
              value: /cache
            - name: TRANSFORMERS_CACHE
              value: /cache
            - name: TZ
              value: Europe/London
          ports:
            - containerPort: 3003
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: "4"
              memory: 6Gi
          volumeMounts:
            - name: model-cache
              mountPath: /cache
          livenessProbe:
            httpGet:
              path: /ping
              port: 3003
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 5
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: immich-model-cache
