apiVersion: v1
kind: Secret
metadata:
  name: lldap-secrets
  namespace: auth
type: Opaque
stringData:
  admin-password: "${LLDAP_ADMIN_PASSWORD}"
  jwt-secret: "${LLDAP_JWT_SECRET}"
  key-seed: "${LLDAP_KEY_SEED}"
