apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
  namespace: auth
spec:
  secretName: authentik-tls
  commonName: auth.apps.house.simonellistonball.com
  dnsNames:
    - auth.apps.house.simonellistonball.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  subject:
    organizations:
      - Simon Elliston Ball
    organizationalUnits:
      - homelab
