apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webhook-relay
  namespace: webhook-relay
  labels:
    app: webhook-relay
spec:
  selector:
    matchLabels:
      app: webhook-relay
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - webhook-relay
