# Cilium LoadBalancer IP Pool - Dual Stack
# Replaces MetalLB IPAddressPool
#
# IP Range Strategy (to avoid CIDR overlap conflicts):
#   IPv4: General pool uses .128-.255 (/25), specific services use .0-.127
#   IPv6: General pool uses :1::/80, specific services use ::/80
#
# Traefik gets dedicated IPs from traefik-pool below.
# General pools have serviceSelector to exclude Traefik services.
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool-v4
spec:
  blocks:
    - cidr: "CILIUM_LB_POOL_V4_PLACEHOLDER"
  serviceSelector:
    matchExpressions:
      - key: io.cilium/lb-ipam-ips
        operator: DoesNotExist
      # Exclude Traefik - it uses dedicated traefik-pool
      - key: app.kubernetes.io/name
        operator: NotIn
        values:
          - traefik
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool-v6
spec:
  blocks:
    - cidr: "CILIUM_LB_POOL_V6_PLACEHOLDER"
  serviceSelector:
    matchExpressions:
      - key: io.cilium/lb-ipam-ips
        operator: DoesNotExist
      # Exclude Traefik - it uses dedicated traefik-pool
      - key: app.kubernetes.io/name
        operator: NotIn
        values:
          - traefik
---
# Pool for Traefik with specific IPs (dual-stack)
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-pool
spec:
  blocks:
    - cidr: "TRAEFIK_IP_PLACEHOLDER/32"
    - cidr: "TRAEFIK_IP_V6_PLACEHOLDER/128"
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
